title: HTML Справочник
subtitle: "Бесплатный справочник по HTML"
description: Бесплатный справочник всех HTML тегов и аттрибутов.
share: "HTML ссылка: бесплатный справочник всех HTML тегов и аттрибутов."
url: https://atomcss.ru/htmlref
destination: "../atomcss.ru/htmlref"
markdown: kramdown
permalink: pretty
exclude: ['node_modules']